'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Frogger.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property auditt_lt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("auditt_lt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property auditt_rt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("auditt_rt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property beetlelt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("beetlelt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property beetleredlt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("beetleredlt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property beetleredrt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("beetleredrt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property beetlert() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("beetlert", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bus_lt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bus_lt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bus_rt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bus_rt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cestrez_lt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cestrez_lt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cestrez_rt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cestrez_rt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cossie() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cossie", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Die() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Die", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property doublelt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("doublelt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property doublert() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("doublert", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fancybug_lt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fancybug_lt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fancybug_rt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fancybug_rt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property firetruck_lt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("firetruck_lt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property firetruck_rt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("firetruck_rt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fly() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fly", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property frog2GrassUp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frog2GrassUp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property frog2RoadUp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frog2RoadUp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property frogger() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("frogger", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property froggerimage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("froggerimage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property froggersplat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("froggersplat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property heart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property loggood() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loggood", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property monsterbug_rt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("monsterbug_rt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property platform() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("platform", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property redtrucklt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redtrucklt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property redtruckrt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redtruckrt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property road() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("road", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property semi_lt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("semi_lt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property semi_rt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("semi_rt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stretch_lt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stretch_lt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stretch_rt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stretch_rt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tanker_lt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tanker_lt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tanker_rt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tanker_rt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property u_jack_lt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("u_jack_lt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property u_jack_rt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("u_jack_rt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property water() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("water", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Win() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Win", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Win2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Win2", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property YouLose() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("YouLose", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
